# Generated by Django 2.2.5 on 2019-09-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutu', '0002_auto_20190920_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutu',
            name='grainsAllowed',
            field=models.TextField(choices=[(1, 'Wheat'), (2, 'jowar'), (3, 'Rice'), (4, 'Bajree'), (5, 'Corn')], default=''),
        ),
    ]
