# Generated by Django 2.2.5 on 2019-09-24 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutu', '0004_auto_20190924_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutu',
            name='grainsAllowed',
        ),
    ]
