# Generated by Django 2.2.5 on 2019-09-24 11:05

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rutu', '0005_remove_rutu_grainsallowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutu',
            name='grainsAllowed',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Wheat'), (2, 'jowar'), (3, 'Rice'), (4, 'Bajree'), (5, 'Corn')], default='', max_length=9),
        ),
    ]
