# Generated by Django 2.2.5 on 2019-09-18 07:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0002_excercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rutu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('fromDate', models.DateTimeField(default=datetime.datetime.now)),
                ('toDate', models.DateTimeField(default=datetime.datetime.now)),
                ('allowedDescr', models.TextField(blank=True)),
                ('notAllowedDescr', models.TextField(blank=True)),
                ('photo_main', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('excersize', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='food.Excercise')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='food.food')),
                ('foodType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='food.foodType')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rutu.Zone')),
            ],
        ),
    ]
