# Generated by Django 2.2.5 on 2019-09-20 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutu',
            name='excersize',
        ),
        migrations.RemoveField(
            model_name='rutu',
            name='food',
        ),
        migrations.RemoveField(
            model_name='rutu',
            name='foodType',
        ),
    ]
