# Generated by Django 2.2.5 on 2019-10-01 06:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_drinks_fruitjuices_fruits_leafyveg_lentils_nonveg_soup_spices_vegetables'),
        ('rutu', '0003_rutugrain'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutuNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('fromDate', models.DateTimeField(default=datetime.datetime.now)),
                ('toDate', models.DateTimeField(default=datetime.datetime.now)),
                ('allowedDescr', models.TextField(blank=True)),
                ('notAllowedDescr', models.TextField(blank=True)),
                ('photo_main', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('grain', models.ManyToManyField(to='food.grain')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rutu.Zone')),
            ],
        ),
    ]
