# Generated by Django 2.2.5 on 2019-10-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_legumes'),
        ('rutu', '0011_rutunew_nonveg'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutunew',
            name='legumes',
            field=models.ManyToManyField(related_name='legumes', to='food.legumes'),
        ),
    ]
