# Generated by Django 2.2.5 on 2019-11-26 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0007_legumes'),
    ]

    operations = [
        migrations.CreateModel(
            name='mealPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealDate', models.DateField()),
                ('mealType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='food.mealType')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='food.Menu')),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
