# Generated by Django 2.2.5 on 2019-09-24 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_grains'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='grains',
            new_name='grain',
        ),
    ]
